var SpaceSim = SpaceSim || {};
SpaceSim.Ships = SpaceSim.Ships || {};

/**
 * Module is a base class for any component that has mass, integrity and cost
 */
SpaceSim.Ships.Module = function(options) {
  if (!options) { options = {}; }
  this.mass = options.mass || 0; // in tonnes
  this.integrity = options.integrity || 0; // multiplier used for calculating damage
  this.currentIntegrity = 100; // 100% is healthy, 0% is broken
  this.cost = options.cost || 0;
};

SpaceSim.Ships.Ship = function(options) {
  SpaceSim.Ships.Module.call(this, options);

  this.hull = new SpaceSim.Ships.Hull(options.hull);
  this.fuelTank = new SpaceSim.Ships.FuelTank(options.fuelTank);

  this.coreModules = new SpaceSim.Ships.CoreModules(options.coreModules);
  this.weaponModules = new SpaceSim.Ships.WeaponModules(options.weaponModules);
  this.defenseModules = new SpaceSim.Ships.DefenseModules(options.defenseModules);
  this.utilityModules = new SpaceSim.Ships.UtilityModules(options.utilityModules);

  // simulates placement of thruster ports; used in conjunction with mass to determine speeds
  this.pitchMultiplier = options.pitchMultiplier || 0;
  this.yawMultiplier = options.yawMultiplier || 0;
  this.rollMultiplier = options.rollMultiplier || 0;
  this.forwardThrustMultiplier = options.forwardThrustMultiplier || 0;
  this.reverseThrustMultiplier = options.reverseThrustMultiplier || 0;
  this.upThrustMultiplier = options.upThrustMultiplier || 0;
  this.downThrustMultiplier = options.downThrustMultiplier || 0;
  this.leftThrustMultiplier = options.leftThrustMultiplier || 0;
  this.rightThrustMultiplier = options.rightThrustMultiplier || 0;
};
SpaceSim.Ships.Ship.prototype = Object.create(SpaceSim.Ships.Module.prototype);
SpaceSim.Ships.Ship.prototype.constructor = SpaceSim.Ships.Ship;
SpaceSim.Ships.Ship.prototype.getHeat = function() {
  // start by getting PowerPlant efficiency and power draw of all enabled modules

  // add heat generated by current actions (weapons fire, thrusting, etc.)

  // add heat from nearby objects (stars, gas giants, etc.)
};
SpaceSim.Ships.Ship.prototype.getTotalMass = function() {
 // add up mass of ship + hull + currentFuel + all modules
 var totalMass = this.mass + this.hull.mass + this.fuelTank.mass + this.fuelTank.currentAmount +
                this.CoreModules.generator.mass + this.CoreModules.thrusters.mass +
                this.CoreModules.warpCore.mass + this.CoreModules.lifeSupport.mass +
                this.CoreModules.capacitor.mass;
};

SpaceSim.Ships.Hull = function(options) {
  SpaceSim.Ships.Module.call(this, options);

  this.thermalResistance = options.thermalResistance || 0;
  this.impactResistance = options.impactResistance || 0;
};
SpaceSim.Ships.Hull.prototype = Object.create(SpaceSim.Ships.Module.prototype);
SpaceSim.Ships.Hull.prototype.constructor = SpaceSim.Ships.Hull;

SpaceSim.Ships.FuelTank = function(options) {
  SpaceSim.Ships.Module.call(this, options);

  this.maxCapacity = options.maxCapacity || 0; // in tonnes
  this.currentAmount = options.currentAmount || 0; // in tonnes
};
SpaceSim.Ships.FuelTank.prototype = Object.create(SpaceSim.Ships.Module.prototype);
SpaceSim.Ships.FuelTank.prototype.constructor = SpaceSim.Ships.FuelTank;

/**
 * PoweredModules extend from a standard Module, but can be
 * turned off or on via the 'enabled' property and will consume
 * power from the installed 'generator' if turned on
 */
SpaceSim.Ships.PoweredModule = function(options) {
  SpaceSim.Ships.Module.call(this, options);

  this.enabled = true; // enabled by default
  this.powerDraw = options.powerDraw || 0; // in megaWatts
};
SpaceSim.Ships.PoweredModule.prototype = Object.create(SpaceSim.Ships.Module.prototype);
SpaceSim.Ships.PoweredModule.prototype.constructor = SpaceSim.Ships.PoweredModule;

SpaceSim.Ships.CoreModules = function(options) {
  this.generator = new SpaceSim.Ships.CoreModules.Generator(options.generator);
  this.thrusters = new SpaceSim.Ships.CoreModules.Thrusters(options.thrusters);
  this.warpCore = new SpaceSim.Ships.CoreModules.WarpCore(options.warpCore);
  this.lifeSupport = new SpaceSim.Ships.CoreModules.LifeSupport(options.lifeSupport);
  this.capacitor = new SpaceSim.Ships.CoreModules.Capacitor(options.capacitor);
};

SpaceSim.Ships.CoreModules.Generator = function(options) {
  SpaceSim.Ships.PoweredModule.call(this, options);

  this.power = options.power || 0; // in megaWatts
  this.efficiency = options.efficiency || 0; // how much heat generated per megaWatt consumed
};
SpaceSim.Ships.CoreModules.Generator.prototype = Object.create(SpaceSim.Ships.PoweredModule.prototype);
SpaceSim.Ships.CoreModules.Generator.prototype.constructor = SpaceSim.Ships.CoreModules.Generator;

SpaceSim.Ships.CoreModules.Thrusters = function(options) {
  SpaceSim.Ships.PoweredModule.call(this, options);

  this.thrust = options.thrust || 0;
};
SpaceSim.Ships.CoreModules.Thrusters.prototype = Object.create(SpaceSim.Ships.PoweredModule.prototype);
SpaceSim.Ships.CoreModules.Thrusters.prototype.constructor = SpaceSim.Ships.CoreModules.Thrusters;

SpaceSim.Ships.CoreModules.WarpCore = function(options) {
  SpaceSim.Ships.PoweredModule.call(this, options);

  this.maximumMass = options.maximumMass || 0; // maximum mass that can be shifted. above maximum the jump range drops to 0
  this.maximumFuel = options.maximumFuel || 0; // maximum fuel used for maximum jump
  this.maximumRange = options.maximumRange || 0; // largest jump range at 0 mass
};
SpaceSim.Ships.CoreModules.WarpCore.prototype = Object.create(SpaceSim.Ships.PoweredModule.prototype);
SpaceSim.Ships.CoreModules.WarpCore.prototype.constructor = SpaceSim.Ships.CoreModules.WarpCore;

SpaceSim.Ships.CoreModules.LifeSupport = function(options) {
  SpaceSim.Ships.PoweredModule.call(this, options);

  this.time = options.time || 0;
};
SpaceSim.Ships.CoreModules.LifeSupport.prototype = Object.create(SpaceSim.Ships.PoweredModule.prototype);
SpaceSim.Ships.CoreModules.LifeSupport.prototype.constructor = SpaceSim.Ships.CoreModules.LifeSupport;

SpaceSim.Ships.CoreModules.Capacitor = function(options) {
  SpaceSim.Ships.PoweredModule.call(this, options);

  this.boostPower = options.boostPower || 0;
  this.boostTime = options.boostTime || 0;
};
SpaceSim.Ships.CoreModules.Capacitor.prototype = Object.create(SpaceSim.Ships.PoweredModule.prototype);
SpaceSim.Ships.CoreModules.Capacitor.prototype.constructor = SpaceSim.Ships.CoreModules.Capacitor;

SpaceSim.Ships.WeaponModules = function(options) {
  this.SIZE_SMALL = 1;
  this.SIZE_MEDIUM = 2;
  this.SIZE_LARGE = 3;

  this.smallCount = options.smallCount || 0;
  this.mediumCount = options.mediumCount || 0;
  this.largeCount = options.largeCount || 0;

  this.smallModules = [this.smallCount];
  this.mediumModules = [this.mediumCount];
  this.largeModules = [this.largeCount];
};
SpaceSim.Ships.WeaponModules.prototype.add = function(weapon) {
  var moduleArray = null;
  var maxModuleCount = 0;
  switch (weapon.size) {
    case SpaceSim.Ships.WeaponModules.SIZE_SMALL:
      moduleArray = this.smallModules;
      maxModuleCount = this.smallCount;
      break;
    case SpaceSim.Ships.WeaponModules.SIZE_MEDUIUM:
      moduleArray = this.mediumModules;
      maxModuleCount = this.mediumCount;
      break;
    case SpaceSim.Ships.WeaponModules.SIZE_LARGE:
      moduleArray = this.largeModules;
      maxModuleCount = this.largeCount;
      break;
    default:
      throw "invalid weapon size specified: " + weapon.size;
  }
  if (moduleArray.length < maxModuleCount) {
    moduleArray.push(weapon);
  }
};

SpaceSim.Ships.WeaponModules.Weapon = function(options) {
  SpaceSim.Ships.PoweredModule.call(this, options);

  this.maxAmmo = options.maxAmmo || 0;
  this.reloadDelay = options.reloadDelay || 0;
  this.thermalDamage = options.thermalDamage || 0;
  this.impactDamage = options.impactDamage || 0;
};
SpaceSim.Ships.WeaponModules.Weapon.prototype = Object.create(SpaceSim.Ships.PoweredModule.prototype);
SpaceSim.Ships.WeaponModules.Weapon.prototype.constructor = SpaceSim.Ships.WeaponModules.Weapon;
SpaceSim.Ships.WeaponModules.Weapon.prototype.enabled = false; // weapons off by default and need be deployed

SpaceSim.Ships.DefenseModules = function(options) {
  this.size = options.size || 0; // Defense modules can be added to occupy all available space

  this.modules = [0];
};

SpaceSim.Ships.UtilityModules = function(options) {
  this.size = options.size || 0; // utility modules can be added to occupy all available space

  this.modules = [0];
};
